In [1]:
print(":")

:


In [2]:
import numpy as np

arr1 = np.array([1, 2, 3])
num =2

result = arr1 + num
print(result)  # Output: [3 4 5]

[3 4 5]


In [3]:
# Broadcasting a 2d array with a 3d array

arr2d = np.arange(9).reshape(3, 3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr1d = np.arange(4)
arr1d

array([0, 1, 2, 3])

In [5]:
result = arr2d + arr1d

result

ValueError: operands could not be broadcast together with shapes (3,3) (4,) 

In [ ]:
arr2d[[0,2]]

array([[0, 1, 2],
       [6, 7, 8]])

In [ ]:
matrix = np.arange(8).reshape(2, 4)
matrix

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
vector = np.array([1, 2, 3, 4])
vector

array([1, 2, 3, 4])

In [7]:
# Broadcasting a 2D matrix with a 1D vector through multiplication
result = matrix * vector
print(result)

NameError: name 'matrix' is not defined

In [8]:
matrix * vector

NameError: name 'matrix' is not defined

List Comprehension

In [9]:
[i*2 for i in range(5) if i % 2 == 0]

[0, 4, 8]

In [10]:
new_list = [a*2 if a%2 ==0 else a*3 for a in range(8)  ]
new_list

[0, 3, 4, 9, 8, 15, 12, 21]

# Dict Comprehension

In [11]:
{a:a**2 for a in range(10)}

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}