# Whats is Numpy? 
        - Numerical Python: maths stats, sciences , physics
        - Its an array. Not similar to python list. 
        - Array holds uniform data type.

In [1]:
def squares(values):
    result = []
    for v in values:
        result.append(v * v)
    return result

In [2]:
to_square = range(100000)

In [3]:
%timeit squares(to_square)

7.56 ms ± 328 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
import numpy as np

In [5]:
lst = range(100000)

In [11]:
print(type(lst))

<class 'range'>


In [7]:
arr = np.array(lst) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([    0,     1,     2, ..., 99997, 99998, 99999], shape=(100000,))

In [8]:
arr**2

array([         0,          1,          4, ..., 9999400009, 9999600004,
       9999800001], shape=(100000,))

In [9]:
arr*10

array([     0,     10,     20, ..., 999970, 999980, 999990],
      shape=(100000,))

In [10]:
arr = np.arange(100000)
print(arr)
%timeit arr**2

[    0     1     2 ... 99997 99998 99999]
71 μs ± 1.59 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# Creating Numpy Arrays
    - numpy.array()
    - numpy.arange()
    - type cast python list

# 1D array

In [12]:
lst = [1,2,3,4,5,6,7,8,9,10]
arr = np.array(lst)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.array((1,2,3,4))
arr

array([1, 2, 3, 4])

In [2]:

np.size(arr,1)

NameError: name 'np' is not defined

In [20]:
arr.shape


(4,)

In [21]:
arr.dtype

dtype('int64')

In [19]:
lst = [1,2,3,4,5,'apple']

In [20]:
arr = np.array(lst)
arr

array(['1', '2', '3', '4', '5', 'apple'], dtype='<U21')

In [21]:
arr.ndim

1

In [22]:
lst = [1,2,3,4,5,6,7,8,9,10]
arr = np.array(lst)

In [23]:
arr+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
arr1 = np.arange(20,30)
arr1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
 arr + arr1

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

In [26]:
arr2 = np.arange(9)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (10,) (9,) 

# 2-D Array

In [95]:
lst  = [[1,2,3],[4,5,6],[7,8,9]]
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [96]:
arr2d = np.array(lst)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
arr2d.size

9

In [28]:
arr2d.shape

NameError: name 'arr2d' is not defined

In [29]:
arr2d.ndim

NameError: name 'arr2d' is not defined

In [30]:
arr2d2 = np.arange(9).reshape(3,3)
arr2d2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
arr2d3 = np.arange(50).reshape(25,2)
arr2d3

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

In [32]:
arr2d3[1:3,:1]

array([[2],
       [4]])

In [33]:
arr3d = np.arange(27).reshape(3,3,3) # copy/Depth, Rows , Columns
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [34]:
arr3d.ndim

3

In [35]:
arr3d.shape

(3, 3, 3)

In [36]:
arr = np.array([[10]])
arr.ndim

2

In [48]:
%pip install PIL

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for PIL


In [49]:
# Import the necessary libraries
from PIL import Image

# load the image and convert into
# numpy array
image = Image.open('pic.jpg')
print(type(image))
# asarray() class is used to convert
# PIL images into NumPy arrays
numpydata = np.asarray(image)

# <class 'numpy.ndarray'>
print(type(numpydata))

# shape
print(numpydata.shape)

numpydata

ModuleNotFoundError: No module named 'PIL'

In [50]:
arr = np.arange(100).reshape(10,10)
arr
arr.ndim
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [51]:
arr[0:4,1:3]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32]])

In [52]:
arr[5,7]

np.int64(57)

In [53]:
arr[5:6,7:8]

array([[57]])

In [54]:
arr[-1]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [55]:
arr[:, 9:]

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])

In [56]:
arr[:,5:6]

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55],
       [65],
       [75],
       [85],
       [95]])

In [57]:
numpydata

NameError: name 'numpydata' is not defined

In [58]:
numpydata.shape

NameError: name 'numpydata' is not defined

In [59]:
cropped_image = numpydata[:, :, :]
cropped_image

NameError: name 'numpydata' is not defined

In [60]:
image = Image.fromarray(cropped_image)
image.save('output_img.png')
image.show()

NameError: name 'Image' is not defined

# Practice

In [61]:
import numpy as np

In [62]:
np.array([3,1])

array([3, 1])

In [63]:
a = np.array([[1,0,1], [3,4,1]])
a

array([[1, 0, 1],
       [3, 4, 1]])

In [64]:
a = np.array([ [ [ 1 , 7 , 9 ], 
[ 5 , 9 , 3 ],
[ 7 , 9 , 9 ] ], 
[ [ 1 , 2 , 6 ], 
[ 5 , 9 , 0 ],
[ 2 , 0 , 3 ] ] ] )


In [65]:
a

array([[[1, 7, 9],
        [5, 9, 3],
        [7, 9, 9]],

       [[1, 2, 6],
        [5, 9, 0],
        [2, 0, 3]]])

In [66]:
a1 = np.arange(1,10)
print(a1)
a1[3:8]

[1 2 3 4 5 6 7 8 9]


array([4, 5, 6, 7, 8])

In [67]:
a1[::2]

array([1, 3, 5, 7, 9])

In [68]:
a1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [69]:
a1[9:0:-1]

array([9, 8, 7, 6, 5, 4, 3, 2])

In [70]:
m = np.arange(0,20).reshape(5,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [71]:
m[1:4:2,1:4:2]

array([[ 5,  7],
       [13, 15]])

In [72]:
np.size(m)

20

In [73]:
# For Rows
np.size(m,0)

5

In [74]:
# For Column
np.size(m,1)

4

In [75]:
m[1,0]

np.int64(4)

In [76]:
m[:,2]

array([ 2,  6, 10, 14, 18])

In [77]:
m[:,1]

array([ 1,  5,  9, 13, 17])

In [78]:
m[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [79]:
m[3:5,1:3]

array([[13, 14],
       [17, 18]])

In [80]:
m[[1,3,4],:]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [81]:
array = np.arange(60).reshape(3,4,5)
array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [82]:
element = [1,2,3]
print(element
     )

[1, 2, 3]


In [83]:
layer = array[0,:,:]
layer

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [84]:
layers = array[:,:1,:]
layers

array([[[ 0,  1,  2,  3,  4]],

       [[20, 21, 22, 23, 24]],

       [[40, 41, 42, 43, 44]]])

In [85]:
layers2 = array[:,:,:3]
layers2

array([[[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17]],

       [[20, 21, 22],
        [25, 26, 27],
        [30, 31, 32],
        [35, 36, 37]],

       [[40, 41, 42],
        [45, 46, 47],
        [50, 51, 52],
        [55, 56, 57]]])

In [86]:
# Ellipsis

array[1, ...]

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])