# Combining Arrays

* Horizontal Stack axis =0
* Vertical Stack   axis =1
* Depth Stack   

In [1]:
import numpy as np
a = np.zeros((4,4))
b = np.ones((4,4))


In [2]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.hstack((a,b))

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [5]:
np.vstack((a,b))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.dstack((a,b))

array([[[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]]])

In [2]:
import numpy as np
a = np.arange(16).reshape(4,4)
b = np.arange(16,32).reshape(4,4)

np.dstack((a,b))

array([[[ 0, 16],
        [ 1, 17],
        [ 2, 18],
        [ 3, 19]],

       [[ 4, 20],
        [ 5, 21],
        [ 6, 22],
        [ 7, 23]],

       [[ 8, 24],
        [ 9, 25],
        [10, 26],
        [11, 27]],

       [[12, 28],
        [13, 29],
        [14, 30],
        [15, 31]]])

In [3]:
np.concatenate((a,b),axis =1)

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [4]:
np.concatenate((a,b),axis =0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [5]:
np.hstack((a,b))

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [6]:
np.vstack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

* hstack == col_stack == axis == 1
* vstack == row_stack == axis == 0

# Splitting Arrays

In [7]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
np.split(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [9]:
np.hsplit(a,2)


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [10]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [11]:
print(np.split(a,2,axis=1))
print('-------------------------------------------')
print(np.split(a,2,axis=0))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
-------------------------------------------
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# Useful Numerical Methods of Numpy Arrays

In [12]:
m = np.arange(10,19).reshape(3,3)

In [13]:
m

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [14]:
print("{} min of the entire matrix".format(m.min()))

10 min of the entire matrix


In [15]:
print("{} max of the entire matrix".format(m.max()))

18 max of the entire matrix


In [16]:
print("{} min args of the entire matrix".format(m.argmin
                                           ()))

0 min args of the entire matrix


In [17]:
print("{} max arg of the entire matrix".format(m.argmax()))

8 max arg of the entire matrix


In [18]:
print("{} min row of the entire matrix".format(m.min(axis = 0)))

[10 11 12] min row of the entire matrix


In [19]:
print("{} min col of the entire matrix".format(m.min(axis=1)))

[10 13 16] min col of the entire matrix


In [20]:
m.mean()

np.float64(14.0)

In [21]:
m.std()

np.float64(2.581988897471611)

In [22]:
m.var()

np.float64(6.666666666666667)

Distance from the mean is known as variance

In [23]:
m.sum()

np.int64(126)

In [24]:
m.prod()

np.int64(17643225600)

In [26]:
m.cumsum()

array([ 10,  21,  33,  46,  60,  75,  91, 108, 126])

In [28]:
print(m.cumsum(axis=0))
print('-------------------------------------------')
print(m.cumsum(axis=1))

[[10 11 12]
 [23 25 27]
 [39 42 45]]
-------------------------------------------
[[10 21 33]
 [13 27 42]
 [16 33 51]]


In [32]:
(m > 5).any() , (m<10).all()

(np.True_, np.False_)

# Fancy Indexing

In [35]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
a[[1,0,2],[0,1,2]] # fancy indexing

array([3, 1, 8])

In [45]:
# For supposition i first want second col then first col

a[:,[2,1]] # fancy indexing

array([[2, 1],
       [5, 4],
       [8, 7]])

# Transposing Arrays and Swapping Axes

In [49]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [50]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [52]:
# It multiplies the matrix with its transpose
np.dot(arr,arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [53]:
# The @ infix operator is another way to do matrix multiplication:
arr @ arr.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [54]:
# ndarray has also a special method for swqpping axes if needed:
# This is useful for multidimensional arrays, but in this case it is equivalent to the transpose:
arr.swapaxes(0,1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])