In [3]:
import numpy as np

In [4]:
data = np.array([[1.5,-0.1, 3.],[0.,-3.,6.5]])

data.dtype


dtype('float64')

In [5]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [7]:
data.shape

(2, 3)

In [8]:
# The 0 tells numpy to count how many rows are in our data table
# Just like counting how many lines are in your notebook!
# In this case, we have 2 rows in our data
np.size(data,0)

2

In [9]:
data.shape

(2, 3)

In [10]:
lst = np.array([[1,2,3],[4,5,6]])

np.size(lst)

6

In [11]:
lst.ndim


2

In [12]:
lst.shape


(2, 3)

In [13]:
lst = np.arange(75).reshape(5,15)
lst

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74]])

In [14]:
print(lst.ndim)

print(lst.shape)

print(np.size(lst,1))

2
(5, 15)
15


In [17]:
lst[0:3:1,5:6:]




array([[ 5],
       [20],
       [35]])

In [18]:
arr = np.arange(16).reshape(4,4)

arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
arr[-4:-1,-4:2]


array([[0, 1],
       [4, 5],
       [8, 9]])