In [2]:
import numpy as np

In [4]:
data = np.array([[1.5,-0.1, 3.],[0.,-3.,6.5]])

data.dtype


dtype('float64')

In [5]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [7]:
data.shape

(2, 3)

In [8]:
# The 0 tells numpy to count how many rows are in our data table
# Just like counting how many lines are in your notebook!
# In this case, we have 2 rows in our data
np.size(data,0)

2

In [9]:
data.shape

(2, 3)

In [10]:
lst = np.array([[1,2,3],[4,5,6]])

np.size(lst)

6

In [11]:
lst.ndim


2

In [12]:
lst.shape


(2, 3)

In [9]:
lst = np.arange(75).reshape(5,15)
lst

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74]])

In [10]:
print(lst.ndim)

print(lst.shape)

print(np.size(lst,1))

2
(5, 15)
15


In [11]:
lst[0:3:1,5:6:]




array([[ 5],
       [20],
       [35]])

In [12]:
arr = np.arange(16).reshape(4,4)

arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
arr[-4:-1,-4:2]


array([[0, 1],
       [4, 5],
       [8, 9]])

In [14]:
arr3d = np.arange(16).reshape(2,4,2)

In [20]:
print(arr3d)

arr3d.ndim

print(arr3d.shape)

arr3d.size


[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]
(2, 4, 2)


16

In [16]:
np.size(arr3d,2)

2

In [17]:
np.size(arr,1)

4

In [18]:
arr.shape

(4, 4)

In [1]:
!pip install Pillow

   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.6 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.6 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.6 MB 599.9 kB/s eta 0:00:04
   ------- -------------------------------- 0.5/2.6 MB 599.9 kB/s eta 0:00:04
   ------- -------------------------------- 0.5/2.6 MB 599.9 kB/s eta 0:00:04
   ----------- ---------------------------- 0.8/2.6 MB 424.9 kB/s eta 0:00:05
   ----------- ---------------------------- 0.8/2.6 MB 424.9 kB/s eta 0:00:05
   --------------- ------------------------ 1.0/2.6 MB 484.0 kB/s eta 0:00:04
   --------------- ------------------------ 1.0/2.6 MB 484.0 kB/s eta 0:00:04
   --------------- ------------------------ 1.0/2.6 MB 484.0 kB/s eta 0:00:04
   ------------------- --------

In [90]:
from PIL import Image
import numpy as np

img = Image.open('images.jpeg')

img

numpy_img = np.asarray(img)

print(type(numpy_img))
print(numpy_img.shape)

numpy_img.ndim

numpy_img.ndim


<class 'numpy.ndarray'>
(183, 275, 3)


3

In [87]:
arr = np.arange(16).reshape(2,2,2,2)
arr

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [88]:
arr[1:3,0:1]

array([[[[ 8,  9],
         [10, 11]]]])

In [89]:
arr.shape
arr.ndim

4

In [93]:
arr[:,1:2,0:1,0:1]

array([[[[ 4]]],


       [[[12]]]])

In [35]:
np.size(arr,3)


2

In [75]:
arr = np.arange(100).reshape(10,10)


In [76]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [77]:
arr[1:3,0:1]

array([[10],
       [20]])

In [78]:
arr[2,4] # Indexing

np.int64(24)

In [79]:
arr[5][7]

np.int64(57)

In [80]:
# This is in python
lst = [[1,2,3,4,5],[6,7,8,9,10]]

lst[0]





[1, 2, 3, 4, 5]

In [81]:
arr3d = np.arange(27).reshape(3,3,3)
arr3d


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [94]:
arr3d[1:3,:,1:2]

array([[[10],
        [13],
        [16]],

       [[19],
        [22],
        [25]]])

In [2]:
import numpy as np

np.empty((2,3,2))

array([[[1.51637889e-311, 1.51637889e-311],
        [1.51637889e-311, 1.26974871e-321],
        [0.00000000e+000, 1.42423689e+160]],

       [[2.10716427e-076, 1.73681492e-047],
        [5.49267105e+174, 1.04829014e+165],
        [6.70395781e+170, 3.45125894e-032]]])

In [4]:
arr =  np.zeros(10)
arr.dtype

dtype('float64')

In [5]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
# Numpy.arange() is resembled to range func in python

np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
lst = [1,2,3]

lst_np = np.asarray(lst)
lst_np.shape

(3,)

In [13]:
# The -1 tells NumPy to automatically infer the number of rows based on the total size
# Since there are 5 elements in total, the resulting shape is (3, 1).
lst_np = np.asarray([1, 2, 3,4,5]).reshape(-1, 1)
lst_np

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [14]:
lst_one = np.ones((2,3))
lst_one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
lst_one_lke = np.ones_like(lst_np)
lst_one_lke

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [17]:
zeros = np.zeros((2,5))

In [18]:
zeros_lke= np.zeros_like(lst_one)
zeros_lke

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
emp = np.empty((2,4))

In [21]:
emp

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
emp = lst_one
emp

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
emp_lke = np.empty_like(lst_one)

In [28]:
emp_lke

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
eye_matrix  = np.eye(3) 
eye_matrix.dtype

dtype('float64')

In [7]:
idt_mt = np.identity(4)
idt_mt.dtype

dtype('float64')

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
np.eye(N=3,M=2 ,k=1, dtype=int,device="cpu") # M is the no of column 
                # K refers to the index of diagonal by default is set to zero
                # dtype refers to the data type in return in this case is int 
                # The device on which to place the created array.

array([[0, 1],
       [0, 0],
       [0, 0]])

In [44]:
dicts =np.identity(6,dtype=dict)   # the difference between the eye and the identity is eye has the
               # opt. to select the no of cols. where the identity is n x n
dicts

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=object)

In [53]:
# You can explicitly convert any data into another by explicitly casting
# it using the method as type

arr=np.array([1,2,4,5,6])
print(arr.dtype)
floated_arr = arr.astype("float")
print(floated_arr.dtype)

int64
float64


In [58]:
# Truncating integer to float the decimal part will be truncated
from numpy import float64


arr=np.arange(5,dtype="float")
arr.dtype

dtype('float64')

In [59]:
integer_arr = arr.astype('int')
integer_arr.dtype

dtype('int64')

In [61]:
# If you have an array of strings representing numbers, you can use astype to
# convert them to numeric form:

str_arr = np.array(['1','2','43'])
str_arr.dtype

dtype('<U2')

In [62]:
int_arr = str_arr.astype('int')
int_arr.dtype

dtype('int64')

In [77]:
# Before, I was a bit
# lazy and wrote float instead of np.float64; NumPy aliases the Python
# types to its own equivalent data types.

# You can also use another array's dtype attribute 

int_arr = np.arange(10)

calibered = np.array([.1,.2,.4,.5,.6,.7,.8],dtype=np.float64)

int_arr = int_arr.astype(calibered.dtype)
int_arr
int_arr = [[1,2,34,56],[90,87,65,31]]
int_arr = np.array(int_arr)

In [67]:
zeros_int_u32 = np.zeros(8,dtype='u4')

zeros_int_u32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [68]:
def main(arr,*abc,**cdcd):
    print(arr)
    print(abc)
    print(cdcd)

main('123',78,"hello",90.98764,name ="Muhammad Ali",cast = "Kazmi", age = 19)

123
(78, 'hello', 90.98764)
{'name': 'Muhammad Ali', 'cast': 'Kazmi', 'age': 19}


In [81]:
np.size(int_arr,1)
int_arr.shape
int_arr.size
int_arr.ndim

2

In [ ]:
reshapes = np.arange(49).reshape(7,7)
print(reshapes)


print(reshapes[1:3,1:2]) #Slicing
reshapes[3,5] #Indexing

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]
[[ 8]
 [15]]


np.int64(26)

In [110]:
d3_arr = np.arange(27).reshape(3,3,3)
d3_arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [116]:
d3_arr[1:3,:,:1] #In 3d slicing first is the depth then row and then column

array([[[ 9],
        [12],
        [15]],

       [[18],
        [21],
        [24]]])

In [117]:
d3_arr.ndim

3

In [118]:
d3_arr.shape

(3, 3, 3)

In [119]:
d3_arr.size

27

In [140]:
arr = np.arange(10)

arr[5:8] = 12

arr_sliced = arr[5:8]
arr_sliced

array([12, 12, 12])

In [141]:
arr_sliced[1] = 16782663

arr

array([       0,        1,        2,        3,        4,       12,
       16782663,       12,        8,        9])

In [121]:
rand_num = np.random.randn(10)
rand_num

array([ 1.03187944, -0.58981461,  0.26982134,  1.43315216, -0.09149027,
       -2.02761792,  1.49161695,  0.67536742,  0.29162633, -0.54894251])

In [122]:
rand_num > 0.7

array([ True, False, False,  True, False, False,  True, False, False,
       False])

In [123]:
rand_num[rand_num > 0.7]

array([1.03187944, 1.43315216, 1.49161695])

# Boolean Selection

In [127]:
rand_num

array([ 1.03187944, -0.58981461,  0.26982134,  1.43315216, -0.09149027,
       -2.02761792,  1.49161695,  0.67536742,  0.29162633, -0.54894251])

In [128]:
rand_num < 1

array([False,  True,  True, False,  True,  True, False,  True,  True,
        True])

In [131]:
rand_num[[False,  True,  True, False,  True,  True, False,  True,  True,
        True]]

array([-0.58981461,  0.26982134, -0.09149027, -2.02761792,  0.67536742,
        0.29162633, -0.54894251])

# Masking 