In [3]:
import numpy as np

In [4]:
data = np.array([[1.5,-0.1, 3.],[0.,-3.,6.5]])

data.dtype


dtype('float64')

In [5]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [7]:
data.shape

(2, 3)

In [8]:
# The 0 tells numpy to count how many rows are in our data table
# Just like counting how many lines are in your notebook!
# In this case, we have 2 rows in our data
np.size(data,0)

2

In [9]:
data.shape

(2, 3)

In [10]:
lst = np.array([[1,2,3],[4,5,6]])

np.size(lst)

6

In [11]:
lst.ndim


2

In [12]:
lst.shape


(2, 3)

In [9]:
lst = np.arange(75).reshape(5,15)
lst

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74]])

In [10]:
print(lst.ndim)

print(lst.shape)

print(np.size(lst,1))

2
(5, 15)
15


In [11]:
lst[0:3:1,5:6:]




array([[ 5],
       [20],
       [35]])

In [12]:
arr = np.arange(16).reshape(4,4)

arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
arr[-4:-1,-4:2]


array([[0, 1],
       [4, 5],
       [8, 9]])

In [14]:
arr3d = np.arange(16).reshape(2,4,2)

In [20]:
print(arr3d)

arr3d.ndim

print(arr3d.shape)

arr3d.size


[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]
(2, 4, 2)


16

In [16]:
np.size(arr3d,2)

2

In [17]:
np.size(arr,1)

4

In [18]:
arr.shape

(4, 4)

In [1]:
!pip install Pillow

   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.6 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.6 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.6 MB 599.9 kB/s eta 0:00:04
   ------- -------------------------------- 0.5/2.6 MB 599.9 kB/s eta 0:00:04
   ------- -------------------------------- 0.5/2.6 MB 599.9 kB/s eta 0:00:04
   ----------- ---------------------------- 0.8/2.6 MB 424.9 kB/s eta 0:00:05
   ----------- ---------------------------- 0.8/2.6 MB 424.9 kB/s eta 0:00:05
   --------------- ------------------------ 1.0/2.6 MB 484.0 kB/s eta 0:00:04
   --------------- ------------------------ 1.0/2.6 MB 484.0 kB/s eta 0:00:04
   --------------- ------------------------ 1.0/2.6 MB 484.0 kB/s eta 0:00:04
   ------------------- --------

In [90]:
from PIL import Image
import numpy as np

img = Image.open('images.jpeg')

img

numpy_img = np.asarray(img)

print(type(numpy_img))
print(numpy_img.shape)

numpy_img.ndim

numpy_img.ndim


<class 'numpy.ndarray'>
(183, 275, 3)


3

In [87]:
arr = np.arange(16).reshape(2,2,2,2)
arr

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [88]:
arr[1:3,0:1]

array([[[[ 8,  9],
         [10, 11]]]])

In [89]:
arr.shape
arr.ndim

4

In [93]:
arr[:,1:2,0:1,0:1]

array([[[[ 4]]],


       [[[12]]]])

In [35]:
np.size(arr,3)


2

In [75]:
arr = np.arange(100).reshape(10,10)


In [76]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [77]:
arr[1:3,0:1]

array([[10],
       [20]])

In [78]:
arr[2,4] # Indexing

np.int64(24)

In [79]:
arr[5][7]

np.int64(57)

In [80]:
# This is in python
lst = [[1,2,3,4,5],[6,7,8,9,10]]

lst[0]





[1, 2, 3, 4, 5]

In [81]:
arr3d = np.arange(27).reshape(3,3,3)
arr3d


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [94]:
arr3d[1:3,:,1:2]

array([[[10],
        [13],
        [16]],

       [[19],
        [22],
        [25]]])