In [2]:
import numpy as np

In [3]:
arr2d=np.arange(25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
arr1d = np.ravel(arr2d)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [7]:
arr = np.array([1,2,3])

In [10]:
new = np.append(arr1d,arr)

In [11]:
new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24,  1,  2,  3])

In [12]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Combining arrays

In [13]:
arr1d= np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr2d = arr1d.reshape(5,2)
arr2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
arr2d[4,1] = 90

In [17]:
arr2d

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8, 90]])

In [18]:
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 90])

In [19]:
arr1d_a= np.arange(20,30)
arr1d_a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
new_array = arr1d_a.reshape(5,2) + arr1d.reshape(5,2)

In [21]:
new_array

array([[ 20,  22],
       [ 24,  26],
       [ 28,  30],
       [ 32,  34],
       [ 36, 119]])

In [23]:
new_array[1,1] = 200

In [24]:
new_array

array([[ 20,  22],
       [ 24, 200],
       [ 28,  30],
       [ 32,  34],
       [ 36, 119]])

In [25]:
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 90])

In [26]:
import pandas as pd

In [31]:
data = pd.read_excel("employee.xlsx")
data.values[0]

array([1, 1101, 'Manager', 'Accounts', 50.0, 200000.0], dtype=object)

In [38]:
arr2d_a = np.arange(16).reshape(4,4)
arr2d_b = np.arange(16,32).reshape(4,4)
arr2d_a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
arr2d_b

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [41]:
np.hstack((arr2d_a,arr2d_b))

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [42]:
np.vstack((arr2d_a,arr2d_b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [43]:
np.dstack((arr2d_a,arr2d_b))

array([[[ 0, 16],
        [ 1, 17],
        [ 2, 18],
        [ 3, 19]],

       [[ 4, 20],
        [ 5, 21],
        [ 6, 22],
        [ 7, 23]],

       [[ 8, 24],
        [ 9, 25],
        [10, 26],
        [11, 27]],

       [[12, 28],
        [13, 29],
        [14, 30],
        [15, 31]]])

In [44]:
np.concatenate((arr2d_a, arr2d_b), axis = 1) # horizontal

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [47]:
np.concatenate((arr2d_a, arr2d_b), axis = 0) # vertical stack

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [48]:
np.column_stack((arr2d_a, arr2d_b))

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [49]:
np.row_stack((arr2d_a, arr2d_b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

# Splitting arrays

In [50]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
np.hsplit(arr2d,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [57]:
np.hsplit(arr2d,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [58]:
np.vsplit(arr2d,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [59]:
np.vsplit(arr2d,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [61]:
np.split(arr2d,4,axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [62]:
np.split(arr2d,4,axis=0)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

# Useful numerical methods of NumPy arrays

In [65]:
m = np.arange(10, 19).reshape(3, 3)
print (m)
print ("{0} min of the entire matrix".format(m.min()))
print ("{0} max of entire matrix".format(m.max()))
print ("{0} position of the min value".format(m.argmin()))
print ("{0} position of the max value".format(m.argmax()))
print ("{0} mins down each column".format(m.min(axis = 0)))

[[10 11 12]
 [13 14 15]
 [16 17 18]]
10 min of the entire matrix
18 max of entire matrix
0 position of the min value
8 position of the max value
[10 11 12] mins down each column


In [66]:
print ("{0} mins across each row".format(m.min(axis = 1)))


[10 13 16] mins across each row
[16 17 18] maxs down each column


In [67]:
print ("{0} maxs down each column".format(m.max(axis = 0)))

[16 17 18] maxs down each column


In [69]:
# mean is the centre of data.
# variance is distance of a data point from the mean.
# Standard deviation is the unit of variance. 

arr1d.mean(), arr1d.std(), arr1d.var()

(12.6, 25.916018212680747, 671.6400000000001)

In [70]:
arr1d.sum(), arr1d.prod()

(126, 0)

In [72]:
arr1d.cumsum(), arr1d_a.cumprod()

(array([  0,   1,   3,   6,  10,  15,  21,  28,  36, 126]),
 array([         20,         420,        9240,      212520,     5100480,
          127512000,  -979655296,  -680889216, -1885028864,  1168737792]))

In [73]:
(arr1d>10).any()

True

In [74]:
arr1d[(arr1d>10)]

array([90])

In [76]:
(arr1d <100).all()

True

# Fancy Indexing

In [77]:
f = np.random.randn(5,5)

In [78]:
f

array([[ 0.43150075, -1.44777755,  1.46579941,  1.10498181, -0.06865567],
       [ 0.17228292, -0.7201215 ,  1.54829914, -0.02654745,  0.98033297],
       [-0.1394055 ,  0.13910669,  0.89435454, -0.6589821 , -0.43932185],
       [ 0.3903306 , -0.28602327, -2.57847478, -1.3559217 ,  1.02116228],
       [ 1.9962831 ,  1.8452966 ,  0.45747942,  0.57910092, -0.67822576]])

In [79]:
f[0]

array([ 0.43150075, -1.44777755,  1.46579941,  1.10498181, -0.06865567])

In [81]:
f[:,0:1]

array([[ 0.43150075],
       [ 0.17228292],
       [-0.1394055 ],
       [ 0.3903306 ],
       [ 1.9962831 ]])

In [83]:
f[[4,1,0,3,4,4,4]]

array([[ 1.9962831 ,  1.8452966 ,  0.45747942,  0.57910092, -0.67822576],
       [ 0.17228292, -0.7201215 ,  1.54829914, -0.02654745,  0.98033297],
       [ 0.43150075, -1.44777755,  1.46579941,  1.10498181, -0.06865567],
       [ 0.3903306 , -0.28602327, -2.57847478, -1.3559217 ,  1.02116228],
       [ 1.9962831 ,  1.8452966 ,  0.45747942,  0.57910092, -0.67822576],
       [ 1.9962831 ,  1.8452966 ,  0.45747942,  0.57910092, -0.67822576],
       [ 1.9962831 ,  1.8452966 ,  0.45747942,  0.57910092, -0.67822576]])

In [84]:
f[:,[2,0,3,1]]

array([[ 1.46579941,  0.43150075,  1.10498181, -1.44777755],
       [ 1.54829914,  0.17228292, -0.02654745, -0.7201215 ],
       [ 0.89435454, -0.1394055 , -0.6589821 ,  0.13910669],
       [-2.57847478,  0.3903306 , -1.3559217 , -0.28602327],
       [ 0.45747942,  1.9962831 ,  0.57910092,  1.8452966 ]])

# Transposing Arrays and Swapping Axes

In [85]:
f.T

array([[ 0.43150075,  0.17228292, -0.1394055 ,  0.3903306 ,  1.9962831 ],
       [-1.44777755, -0.7201215 ,  0.13910669, -0.28602327,  1.8452966 ],
       [ 1.46579941,  1.54829914,  0.89435454, -2.57847478,  0.45747942],
       [ 1.10498181, -0.02654745, -0.6589821 , -1.3559217 ,  0.57910092],
       [-0.06865567,  0.98033297, -0.43932185,  1.02116228, -0.67822576]])

In [86]:
f.transpose()

array([[ 0.43150075,  0.17228292, -0.1394055 ,  0.3903306 ,  1.9962831 ],
       [-1.44777755, -0.7201215 ,  0.13910669, -0.28602327,  1.8452966 ],
       [ 1.46579941,  1.54829914,  0.89435454, -2.57847478,  0.45747942],
       [ 1.10498181, -0.02654745, -0.6589821 , -1.3559217 ,  0.57910092],
       [-0.06865567,  0.98033297, -0.43932185,  1.02116228, -0.67822576]])

# Universal Functions: Fast Element-Wise ArrayFunctions

In [87]:
import math

In [88]:
math.ceil(12.9)

13

In [89]:
math.ceil(12.1)

13

In [90]:
math.floor(12.9), math.floor(12.1)

(12, 12)

# Linear Algebra

# Matrix Multiplication

In [5]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x.shape

(2, 3)

In [10]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [7]:
x * y

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [8]:
x@y

array([[ 28.,  64.],
       [ 67., 181.]])

In [9]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [12]:
from numpy.linalg import inv, qr

In [13]:
X = np.random.randn(5, 5)
X

array([[ 1.05768589, -1.19451128, -1.96581836, -1.15790735, -0.41342218],
       [-0.02960965,  1.49652783,  0.68796498,  0.56596201, -2.14138073],
       [ 1.67708161,  0.05059584, -0.14290853, -0.55261504, -0.24267975],
       [ 0.09050862,  1.3803283 , -1.48864917, -0.85311165,  0.64679844],
       [ 1.49039078, -0.09159695,  0.37380032, -0.81247563, -0.16252503]])

In [15]:
X_inv = inv(X)

In [17]:
X@X_inv

array([[ 1.00000000e+00, -8.86935133e-17,  2.92621601e-16,
         1.13863654e-16, -2.30858865e-16],
       [ 2.62970945e-17,  1.00000000e+00, -6.03289999e-18,
        -3.00953638e-17, -2.80590930e-17],
       [-2.71118677e-17,  1.30879280e-17,  1.00000000e+00,
        -4.64365890e-18, -1.04351593e-16],
       [ 9.97006441e-17, -2.89145789e-17, -2.55481884e-16,
         1.00000000e+00,  2.53818219e-16],
       [-1.49392610e-17, -1.16169867e-17,  2.79995688e-16,
        -7.50537766e-17,  1.00000000e+00]])

In [18]:
a = np.array([1.234,5.345,7.8])

In [21]:
np.modf(a)

(array([0.234, 0.345, 0.8  ]), array([1., 5., 7.]))

In [22]:
qr(X)

QRResult(Q=array([[-0.42609723,  0.42539975,  0.60241138,  0.27098603,  0.44849002],
       [ 0.01192848, -0.64532245, -0.17523154,  0.47550939,  0.57149049],
       [-0.67562576, -0.16736725, -0.12846823,  0.42269857, -0.56598576],
       [-0.03646212, -0.60543482,  0.69420297, -0.33885897, -0.18808515],
       [-0.60041586, -0.08961508, -0.32859182, -0.63793254,  0.34137872]]), R=array([[-2.48226417,  0.49731197,  0.7722325 ,  1.39242266,  0.38857427],
       [ 0.        , -2.30984625, -0.38851779, -0.17599827,  0.86959841],
       [ 0.        ,  0.        , -2.44267772, -1.05097728,  0.65977764],
       [ 0.        ,  0.        ,  0.        ,  0.52914312, -1.3483521 ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -1.44897692]]))

# Broadcasting

In [23]:
a

array([1.234, 5.345, 7.8  ])

In [24]:
a * 50

array([ 61.7 , 267.25, 390.  ])

In [28]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
y = np.arange(4)
y

array([0, 1, 2, 3])

In [30]:
x+y 

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

# Pandas
  - Pandas Data Structure
      - Series : One Column
      - DataFrame : Multiple Columns

# Series

#### creating a series

In [2]:
import pandas as pd

In [3]:
s1  = pd.Series([10,20,30,40,20,60])
s1

0    10
1    20
2    30
3    40
4    20
5    60
dtype: int64

##### Components: Values, Indices, Dtype, Title

In [4]:
s1.values

array([10, 20, 30, 40, 20, 60], dtype=int64)

In [5]:
s1.index

RangeIndex(start=0, stop=6, step=1)

In [6]:
s1.dtype

dtype('int64')

In [7]:
s1.name

In [8]:
s2  = pd.Series([10,20,30,40,20,60], index=['Ahmed',"Babar","Choto","Danish","Elephant","Fahad"], name="LetterCounts")
s2

Ahmed       10
Babar       20
Choto       30
Danish      40
Elephant    20
Fahad       60
Name: LetterCounts, dtype: int64

In [9]:
s2['Babar']

20

In [10]:
s2['Elephant']

20

In [11]:
s2[4]

C:\Users\Nasir Hussain\AppData\Local\Temp\ipykernel_11512\3737454092.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s2[4]


20

In [12]:
s2['Babar':"Danish"]

Babar     20
Choto     30
Danish    40
Name: LetterCounts, dtype: int64

In [13]:
s2[1:3]

Babar    20
Choto    30
Name: LetterCounts, dtype: int64

In [14]:
s2["Choto"] = 10
s2

Ahmed       10
Babar       20
Choto       10
Danish      40
Elephant    20
Fahad       60
Name: LetterCounts, dtype: int64

In [15]:
s2['test'] = 23

In [16]:
s2

Ahmed       10
Babar       20
Choto       10
Danish      40
Elephant    20
Fahad       60
test        23
Name: LetterCounts, dtype: int64

In [23]:
emp={'name':['Ahmed',"Babar","Choto","Danish","Elephant","Fahad"],
     "age student":[23,34,43,45,54,34],
     'income':[100000,120000,80000,50000,20000,45000]}

In [26]:
df = pd.DataFrame(emp)
df['age student']

0    23
1    34
2    43
3    45
4    54
5    34
Name: age student, dtype: int64

In [19]:
data = pd.read_excel("employee.xlsx",index_col='Serial')

In [20]:
data

Emp_ID Designation  Department   Age    Salary
Serial                                                
1         1101     Manager    Accounts  50.0  200000.0
2         1107     Officer          IT  30.0   80000.0
3         1203     Officer          HR  28.0       NaN
4         1005     Manager          HR  45.0  120000.0
5         2123  Office Boy    Accounts  27.0   45000.0
6         2451  Accountant         NaN  34.0  100000.0
7         1111  Accountant    Accounts   NaN  110000.0
8         1001     Officer          IT  25.0   75000.0
9         1234     Manager          IT  23.0       NaN
10        2156    Engineer  Production  45.0   89000.0
11        6543     Officer  Production  29.0  100000.0
12        3214  Accountant     Account  49.0  123000.0
13        2156    Engineer  Production  45.0   89000.0
14        1098     Officer          IT  25.0  100000.0
15        2912     Officer          IT  31.0   90000.0
16        1222     Officer         NaN  25.0       NaN
17        2156    Engineer  Production  45.0   89000.0
18        2123  Office Boy    Accounts  27.0   45000.0

In [21]:
type(data)

pandas.core.frame.DataFrame

# Columns
       - fetching a column
       - fetching multiple columns
       - adding columns 
       - deleteing columns
       - rename columns

In [27]:
data['Designation']

Serial
1        Manager
2        Officer
3        Officer
4        Manager
5     Office Boy
6     Accountant
7     Accountant
8        Officer
9        Manager
10      Engineer
11       Officer
12    Accountant
13      Engineer
14       Officer
15       Officer
16       Officer
17      Engineer
18    Office Boy
Name: Designation, dtype: object

In [28]:
data[['Designation', "Emp_ID"]]

Designation  Emp_ID
Serial                    
1          Manager    1101
2          Officer    1107
3          Officer    1203
4          Manager    1005
5       Office Boy    2123
6       Accountant    2451
7       Accountant    1111
8          Officer    1001
9          Manager    1234
10        Engineer    2156
11         Officer    6543
12      Accountant    3214
13        Engineer    2156
14         Officer    1098
15         Officer    2912
16         Officer    1222
17        Engineer    2156
18      Office Boy    2123

In [29]:
data['Gender']= ['M','F','M','F','M','F','M','F','M','F','M','F','M','F','M','F','M','F']

In [30]:
data

Emp_ID Designation  Department   Age    Salary Gender
Serial                                                       
1         1101     Manager    Accounts  50.0  200000.0      M
2         1107     Officer          IT  30.0   80000.0      F
3         1203     Officer          HR  28.0       NaN      M
4         1005     Manager          HR  45.0  120000.0      F
5         2123  Office Boy    Accounts  27.0   45000.0      M
6         2451  Accountant         NaN  34.0  100000.0      F
7         1111  Accountant    Accounts   NaN  110000.0      M
8         1001     Officer          IT  25.0   75000.0      F
9         1234     Manager          IT  23.0       NaN      M
10        2156    Engineer  Production  45.0   89000.0      F
11        6543     Officer  Production  29.0  100000.0      M
12        3214  Accountant     Account  49.0  123000.0      F
13        2156    Engineer  Production  45.0   89000.0      M
14        1098     Officer          IT  25.0  100000.0      F
15        2912     Officer          IT  31.0   90000.0      M
16        1222     Officer         NaN  25.0       NaN      F
17        2156    Engineer  Production  45.0   89000.0      M
18        2123  Office Boy    Accounts  27.0   45000.0      F